### ISSUE TITLE
Full screen video 

### ISSUE THREAD

**Issue by hamidabdulmalik** [cloudwebrtc/flutter-webrtc-demo#1]
First of all, thanks for this brave initiative. 

Secondly, is it possible to make the video on mobile full screen? 

Thanks

**Comment by cloudwebrtc** [comment]
Apologies for the late reply, you can try to create a widgets without navigation bar and , which seems to be solved by flutter layout.

**Comment by varunvasista** [comment]
> Apologies for the late reply, you can try to create a widgets without navigation bar and , which seems to be solved by flutter layout.

Can you please let me know any snippet or sample code to make video full screen

**Comment by varunvasista** [comment]
> First of all, thanks for this brave initiative.
> 
> Secondly, is it possible to make the video on mobile full screen?
> 
> Thanks

Hey, did you make the video full screen?

**Comment by mostafaAbdelazim** [comment]
> Hey, did you make the video full screen?

After reading the code in RTCVideoRenderer
you can try this 
    _remoteRenderer.objectFit =
        RTCVideoViewObjectFit.RTCVideoViewObjectFitCover;

**Comment by piyushkb** [comment]
Thank-you working

**Comment by LucasFancation** [comment]
> > Hey, did you make the video full screen?
> 
> After reading the code in RTCVideoRenderer
> you can try this, it worked for me
> _remoteRenderer.objectFit = RTCVideoViewObjectFit.RTCVideoViewObjectFitCover;

Hi, this code is no longer being available, so any suggestions on working on the fullscreen? Thanks
