### ISSUE TITLE
ios can not play sound use demo? android work well

### ISSUE THREAD

**Issue by linguitang** [cloudwebrtc/flutter-webrtc-demo#12]

**Comment by linguitang** [comment]
iphone6s

**Comment by cloudwebrtc** [comment]
No logs?

**Comment by cloudwebrtc** [comment]
I want to help you, but I don't have the money to buy an iphone6s. ;)

**Comment by linguitang** [comment]
Maybe it's too low. I've turned the volume of my cell phone to its maximum, but the sound I hear is still so low that I can hardly hear it.

**Comment by linguitang** [comment]
no error logs.But I found something should be add to info.plist like "Required background modes"("App downloads content from the network","App downloads content in response to push notifications") that not show in README.md

**Comment by linguitang** [comment]
Redmi Node2  os MIUI 9.8.26 same question,it is android os

**Comment by rostopira** [comment]
@linguitang check if sound goes through earpiece, that maybe the issue

**Comment by linguitang** [comment]
> @linguitang check if sound goes through earpiece, that maybe the issue

yes, you are right。

**Comment by linguitang** [comment]
@cloudwebrtc  plugin will fix it?

**Comment by rostopira** [comment]
@linguitang please, read this https://github.com/cloudwebrtc/flutter-webrtc/issues/45

**Comment by linguitang** [comment]
```
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because client depends on flutter_incall_manager from git which requires SDK version <2.0.0, version solving failed.
```
@rostopira
