### ISSUE TITLE
[Flutter 1.2] I run the demo app but I cannot see remote stream video

### ISSUE THREAD

**Issue by kimthangatm** [cloudwebrtc/flutter-webrtc-demo#17]
I run the demo app but I cannot see remote stream video (With an Iphone with a Simulator)

![Can not see remote video](https://user-images.githubusercontent.com/7090588/54212572-b84a0800-4515-11e9-9ace-494983dacfd7.png)

**Comment by rostopira** [comment]
We do not support emulators
Also, this might be related to this issue: https://github.com/cloudwebrtc/flutter-webrtc/issues/56

**Comment by rostopira** [comment]
And yeah, some logs will be much more useful than empty screenshot (what should we do with that?)
Put some effort in debugging, before filling an issue, next time

**Comment by kimthangatm** [comment]
Thanks for support, I try to get 2 real device and its work. I back to close issues but you did it.
