### ISSUE TITLE
Depreceated API warning

### ISSUE THREAD

**Issue by rebootcode** [cloudwebrtc/flutter-webrtc-demo#20]
Hi, I am getting following warning message:

```
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
## Though it installed and is working as mentioned below
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
```

All the "Note" above gives warning about depreciated API

**Comment by rostopira** [comment]
![image](https://user-images.githubusercontent.com/16724952/56080848-e9687180-5e0e-11e9-8c77-4a9e72345d67.png)

**Comment by rostopira** [comment]
![image](https://user-images.githubusercontent.com/16724952/56080854-fab17e00-5e0e-11e9-9219-d58d6c74f5a3.png)

**Comment by rostopira** [comment]
It's just warning
If it's not broken - don't fix it
