### ISSUE TITLE
请问，这个demo 提供的P2P通话的问题

### ISSUE THREAD

**Issue by lanjiachuan** [cloudwebrtc/flutter-webrtc-demo#21]
我使用demo 中的P2P功能 发现 接听方 并没有选择是否接通 而是直接就是接通模式，另外语音模式的时候  视频也是开着的，请问这个需要怎么设置，希望能修改成 微信的那种效果

**Comment by cloudwebrtc** [comment]
您好，demo仅为了展示插件可以正常工作，所以并未提供来电提醒界面，您可以自行修改，思路如下：当被叫端收到offer的时候弹出接听确认界面，之后再走answer流程。关于音频通话显示了视频，这应该是bug，晚一点我会确认一下代码。

发自我的 iPhone
