### ISSUE TITLE
loopback_sample.dart Error: Too few positional arguments

### ISSUE THREAD

**Issue by vasopikof** [cloudwebrtc/flutter-webrtc-demo#22]
My flutter environment is working properly. This is a compilation error I got. 

Initializing gradle...1.9s
Resolving dependencies...3.6s
                                                                        
Compiler message:                                                       
lib/src/basic_sample/loopback_sample.dart:46:65: Error: Too few positional arguments: 1 required, 0 given.
      List<StatsReport> reports = await _peerConnection.getStats();     
                                                                ^       
Compiler failed on ~workdir/flutter-webrtc-demo/lib/main.dart

**Comment by vasopikof** [comment]
#23 solved in local, create a pull request.

**Comment by cloudwebrtc** [comment]
Merged
