### ISSUE TITLE
作者你好，我发现视频通话接通后，屏幕还是会关闭掉

### ISSUE THREAD

**Issue by lanjiachuan** [cloudwebrtc/flutter-webrtc-demo#25]
我在系统中设置了唤醒权限，但是好像无效，我使用您提供的官方的demo，也是同样的问题，请问如何解决这个问题。

**Comment by cloudwebrtc** [comment]
Demo 仅为了展示插件可以正常通话，屏幕唤醒属于系统设置范畴，你可以尝试使用flutter-incall-manager 里面有 [setKeepScreenOn](https://github.com/cloudwebrtc/flutter-incall-manager/blob/master/lib/flutter_incall_manager.dart#L46)
