### ISSUE TITLE
"No video stream for react tag" on IOS simulator

### ISSUE THREAD

**Issue by AdamJonsson** [cloudwebrtc/flutter-webrtc-demo#3]
When I try "GetUserMedia API Test" and make a "call" nothing is happening. Debug console says "No video stream for react tag: (Random string)"

I am pretty new at WebRTC so I may be missing something? Or maybe it is a bug? Can provide more data if needed.

**Comment by AdamJonsson** [comment]
Ahh that makes sense... Thanks for the quick answer!

**Comment by fukemy** [comment]
i got this error on real device? 
```
No video stream for react tag
```
