### ISSUE TITLE
Crash app

### ISSUE THREAD

**Issue by theantiqa** [cloudwebrtc/flutter-webrtc-demo#33]
Hello Team, 

In flutter version 1.8 stable my app working well in both emulator and android android (after flutter build apk).

after that I have upgrade with latest version with 1.9 stable.. but after upgrading flutter. app getting crash when i open in android device  (after flutter build apk). but its working well in emulator. 

so please let me know. you can use flutter-webrtc-demo for creating release apk . and once its working then let me know what kinds of changes i have to do. 

Thanks in Advance

**Comment by cloudwebrtc** [comment]
Please use the latest version
