### ISSUE TITLE
i want to replace this demo.cloudwebrtc.com url with my own server url

### ISSUE THREAD

**Issue by maxbhoria** [cloudwebrtc/flutter-webrtc-demo#36]
I want to setup my own server like demo.cloudwebrtc.com is doing in this example. Please help me in this.

**Comment by cloudwebrtc** [comment]
Hi, You can refer to https://github.com/cloudwebrtc/flutter-webrtc-server for complete code.

**Comment by maxbhoria** [comment]
> Hi, You can fork this repo, then change this line:
> [Https://github.com/cloudwebrtc/flutter-webrtc-demo/blob/master/lib/main.dart#L64](Https://github.com/cloudwebrtc/flutter-webrtc-demo/blob/master/lib/main.dart#L64)

How? I tried to change this url with my janus server url but did not work.

**Comment by cloudwebrtc** [comment]
This demo can only be used for simple one-to-one call testing and depends on [flutter-webrtc-server](https://github.com/cloudwebrtc/flutter-webrtc-server), I guess you want this demo to work with Janus SFU? If so, you need to port the js client SDK in Janus to the flutter/dart version and then rely on flutter-webrtc to actually dock SFU.
