### ISSUE TITLE
Android手机连接服务器异常

### ISSUE THREAD

**Issue by xingzjx** [cloudwebrtc/flutter-webrtc-demo#37]
1.flutter-webrtc-server在Mac电脑上部署成功
2.打开两个浏览器可以视频通讯
3.手机打开谷歌浏览器，也可以通讯，手机和PC浏览器使用的是同一个网
4.在手机运行flutte-webrtc-demo，Basic API测试没有问题
5.打开P2P Call Sample，填写IP地址，如10.10.50.24
最后连接出现异常，定位到代码 HttpClientRequest request = await client.getUrl(
          Uri.parse('https://$host:$port/ws'));
异常提示：SocketException: OS Error: No route to host, errno = 113

**Comment by cloudwebrtc** [comment]
似乎是手机本身路由问题。
