### ISSUE TITLE
question about this project

### ISSUE THREAD

**Issue by Seven7up** [cloudwebrtc/flutter-webrtc-demo#4]
hi 

first, I want to  thank you

I want to make a conference app with this

or like skype more of the two users can join one call

the web client is not running in firefox

Can you guide me

thanks

**Comment by cloudwebrtc** [comment]
@Seven7up To deploy on Firefox, you need a public network server and domain name, and a valid ssl certificate, set to httpd, and wss server, because firefox does not support self-signed certificates.

**Comment by Seven7up** [comment]
> 
> 
> @Seven7up To deploy on Firefox, you need a public network server and domain name, and a valid ssl certificate, set to httpd, and wss server, because firefox does not support self-signed certificates.
> 
> Replace the certificate in flutter-webrtc-server/certs

thanks

but what about this questions

I want to make a conference app with this

or like skype more of the two users can join one call
