### ISSUE TITLE
 Unhandled Exception: NoSuchMethodError: The getter 'closeCode' was called on null.

### ISSUE THREAD

**Issue by sovoereign** [cloudwebrtc/flutter-webrtc-demo#45]
I have been trying for many days still don't understand what problem is this.
My URL is working on the web but not on the app from peer to peer connection dialog.

`https://115.166.***.178:8086/`

I don't get how a mobile device will connect with web video calling.

**Comment by cloudwebrtc** [comment]
There are two points to note about mobile connection:
1. If your web server uses a valid domain name and SSL certificate, the mobile terminal can connect directly.
2. If not, you need to modify the code to connect your self-signed WSS server using the _connectForSelfSignedCert function.

**Comment by sovoereign** [comment]
@cloudwebrtc  yes manually  I have added certificate over the server and it works. and change my IP URL WSS to WS and port 4442 it works from mobile to web.
url= ws//115.166.***.178:4442   it works.

**Comment by Ifavhoney** [comment]
> @cloudwebrtc yes manually I have added certificate over the server and it works. and change my IP URL WSS to WS and port 4442 it works from mobile to web.
> `url= ws//115.166.***.178:4442 ` it works.

This solved my issue. You mean  'url= ws://115.166.***.178:4442 '
