### ISSUE TITLE
working on emulator but not app not opening on mobile after flutter build apk

### ISSUE THREAD

**Issue by Tushar-DCS** [cloudwebrtc/flutter-webrtc-demo#49]
After flutter upgrading (Flutter v1.12.13+hotfix.5)
- When i am run this app in emulator its working well.
- but when i am creating build using "flutter build apk" then crashed means can't open.
can you tell me what changes i have to made during build

**Comment by cloudwebrtc** [comment]
Fixed https://github.com/cloudwebrtc/flutter-webrtc-demo/commit/ea5b122c77b5bd6124dad74dc06cef74c198d3e8

**Comment by Tushar-DCS** [comment]
Is there anything else to add in gradle while creating build?
Ex : while "flutter build apk"
android {
   ...
   defaultConfig {
   ...
      ndk {
            abiFilters  'armeabi','armeabi-v7a'
      }
   }
}

**Comment by Tushar-DCS** [comment]
Thanks its working now.

**Comment by ZatacaSystems** [comment]
Hello!

I have the same problem now, with version 0.2.7 and flutter version v1.12.13+hotfix.8

I create de apk and when I install it it launches and then closes (crashes)

**Comment by satishsoni777** [comment]
Not working for me , please help
