### ISSUE TITLE
NoSuchMethodError (NoSuchMethodError: The getter 'closeCode' was called on null. (Android)

### ISSUE THREAD

**Issue by Ifavhoney** [cloudwebrtc/flutter-webrtc-demo#53]
Hi, would there be any major differences in connecting with an IOS vs Android phone? The demo successfully works with IOS 10; however, fails to compile on Android 28  with `NoSuchMethodError (NoSuchMethodError: The getter 'closeCode' was called on null`

**Comment by cloudwebrtc** [comment]
Fixed https://github.com/cloudwebrtc/flutter-webrtc-demo/commit/3d904fd0c7554c0c125b82be312c933a55e7edc7
