### ISSUE TITLE
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'closeCode' was called on null.

### ISSUE THREAD

**Issue by simanlx** [cloudwebrtc/flutter-webrtc-demo#56]
flutter: connect to wss://192.168.3.6:4443
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'closeCode' was called on null.
Receiver: null
Tried calling: closeCode
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      SimpleWebSocket.connect (package:flutter_webrtc_demo/src/utils/websocket.dart:29:28)
<asynchronous suspension>
#2      Signaling.connect (package:flutter_webrtc_demo/src/call_sample/signaling.dart:292:19)
#3      _CallSampleState._connect (package:flutter_webrtc_demo/src/call_sample/call_sample.dart:50:45)
#4      _CallSampleState.initState (package:flutter_webrtc_demo/src/call_sample/call_sample.dart:32:5)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#9      SingleChildRenderObjectEle<…>

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building Overlay-[LabeledGlobalKey<OverlayState>#3fbe7](state: OverlayState#83867(entries: [OverlayEntry#e2090(opaque: true; maintainState: false), OverlayEntry#e08bc(opaque: false; maintainState: true)])):
The method 'close' was called on null.
Receiver: null
Tried calling: close()

The relevant error-causing widget was: 
  MaterialApp file:///Users/Mr-Han/Desktop/flutter-webrtc-demo-master/lib/main.dart:47:16
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      SimpleWebSocket.close (package:flutter_webrtc_demo/src/utils/websocket.dart:41:13)
#2      Signaling.close (package:flutter_webrtc_demo/src/call_sample/signaling.dart:100:34)
#3      _CallSampleState.deactivate (package:flutter_webrtc_demo/src/call_sample/call_sample.dart:43:40)
#4      StatefulElement.deactivate (package:flutter/src/widgets/framework.dart:4428:12)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by cloudwebrtc** [comment]
Fixed https://github.com/cloudwebrtc/flutter-webrtc-demo/commit/3d904fd0c7554c0c125b82be312c933a55e7edc7
