### ISSUE TITLE
certs

### ISSUE THREAD

**Issue by gedw99** [cloudwebrtc/flutter-webrtc-demo#8]
For DEV
https://blog.filippo.io/mkcert-valid-https-certificates-for-localhost/
https://github.com/FiloSottile/mkcert
- this gets you a VALID HTTPS Cert ! Very needed for testing 
- works for Localhost :)
- works for Mobiles !! 
- Perfect for DEV.
- ALSO BECAUSE it uses proper Trust chain it works in Browsers !

For PROD
https://github.com/jsha/minica
- Perfect for Making CA and user keys on devices.

Can we make a MakeFile to get all this working. Its difficult to test on emulators and real mobiles when the server is not using real certs.

**Comment by cloudwebrtc** [comment]
Thanks, this seems to only be used in localhost or not? 
Can solve firefox's https access to the localhost domain. 
Normally, we use a mobile phone to connect to our LAN ip, but the phone can't modify the hosts domain name binding, and can't access a LAN address through a domain.

**Comment by cloudwebrtc** [comment]
@gedw99 
Resolved here https://github.com/cloudwebrtc/flutter-webrtc-demo/commit/c2b8df683925b362676d26f3faab514a5c9e4b56
